Repository kotekan/kotekan, pull requests merged in 2019-12, with the labels that each got.

#633 Fix index error in frbPostProcess
  lib/stages/frbPostProcess.cpp
Labels: bug, high priority

#655 Update nlohmann::json to 3.7.3
  include/json.hpp
  lib/core/basebandApiManager.cpp
Labels: enhancement

#656 refactor(BranchPrediction): multiple definitions of (un)likely
  lib/hsa/hsaPulsarUpdatePhase.cpp
  lib/stages/beamformingPostProcess.cpp
  lib/stages/frbPostProcess.cpp
  lib/stages/pulsarPostProcess.cpp
  lib/testing/pulsarSimProcess.cpp
  lib/utils/BranchPrediction.hpp
Labels: Cleanup
